### ISSUE TITLE
Authorize LinkedIn throws an Error

### ISSUE THREAD

**Issue by KRRISH96** [orbit-love/linkedin-auth-app#3]
Hi there,

We were trying out the linkedin integration for orbit. Following the [instructions for GH Action wokflow setup](https://github.com/orbit-love/community-ruby-linkedin-orbit/blob/main/docs/FIRST_TIME_INSTRUCTIONS.md).

One time auth App got deployed successfully.

But when we tried to click `Authorize LinkedIn`. It redirects to `/auth/linkedin/` and throws an error (500 status, from heroku logs)

Any help in this regard is highly appreciated.

Thanks!

Screenshots for referene.

<img width="1440" alt="Screenshot 2021-07-27 at 7 23 23 PM" src="https://user-images.githubusercontent.com/22497932/127166101-0ab01727-d64c-49bc-8e0d-8c3a3eb756d9.png">

<img width="1440" alt="Screenshot 2021-07-27 at 7 25 45 PM" src="https://user-images.githubusercontent.com/22497932/127166481-e0ddf5c3-61d5-4969-b306-5e934dbbbfd9.png">

**Comment by bencgreenberg** [comment]
Can you please share your process step by step in a comment here? 

Some questions to consider:

* Did you request the right Marketing API scope from LinkedIn?
* Did you receive the Marketing API approval from LinkedIn before attempting to run the Heroku app?
* Did you add the Heroku app callback URL in the following format `https://example-heroku-app-url.herokuapp.com/auth/linkedin/callback` to your LinkedIn developer app settings inside LinkedIn?
* Did you do the last step before attempting to run the Heroku app?

**Comment by KRRISH96** [comment]
Sure.

1. Yes, we did request `Marketing Developer Platform`.
2. Yes, the label is changed to `verified` and we are able to access `client id and secret` for the same.
3. Used the above creds and `Deploy to Heroku` button from the instructions to deploy and it is successful.
4. Yes, added the callback url `https://our-app-domain-name.herokuapp.com/auth/linkedin/callback` under Aprroved redirect urls.
5. After the deploy ew clicked `view` to load the app. Copied the url and appended with callback endpoint and added to linkedin app. Post this loaded the app and clicked on `Authorize Linkedin` and got the error page (with 500 status in logs).

Not sure, what went wrong.

**Comment by bencgreenberg** [comment]
Thank you. I will try and replicate the error tomorrow as well. Appreciate the details.

**Comment by bencgreenberg** [comment]
Hi @KRRISH96,

I attempted to replicate your error this morning, but I could not.

These were the steps I took:

1. Click the deploy to Heroku button from the [first time setup instructions](https://github.com/orbit-love/community-ruby-linkedin-orbit/blob/main/docs/FIRST_TIME_INSTRUCTIONS.md)
2. Provide the Client ID and Client Secret in the Heroku deployment initial prompts
3. Navigate to the "Auth" tab in the [LinkedIn Developers dashboard](https://linkedin.com/developers/apps)
![Screen Shot 2021-07-28 at 9 07 38](https://user-images.githubusercontent.com/13892277/127272286-ab77ff9f-2e86-4cf9-a498-c7b8c9f8d4c3.png)
4. Provide the new callback URL consisting of the Heroku generated URL + `/auth/linkedin/callback`
![Screen Shot 2021-07-28 at 9 09 03](https://user-images.githubusercontent.com/13892277/127272501-4967b4f0-97a7-48dd-b68f-2bec4df96be2.png)
5. Navigate to the Heroku app and click the big "Authorize LinkedIn" button
6. Sign in to LinkedIn as prompted after clicking the aforementioned button in the previous step
7. LinkedIn redirected back to the Heroku app and I was shown my new LinkedIn API token

Question:

* After you clicked the "Authorize LinkedIn" button in the Heroku app were you directed to sign in to LinkedIn? Did you sign in?

**Comment by KRRISH96** [comment]
Oh, Lemme delete the existing app and retry the flow again.

> After you clicked the "Authorize LinkedIn" button in the Heroku app were you directed to sign in to LinkedIn? Did you sign in?

No, it did not redirect to LinkedIn fo logging in. Directly resulted in error page.

Thanks for looking into it. Lemme redo the flow and get back.

**Comment by KRRISH96** [comment]
Hey @bencgreenberg,

still no luck.

Lemme see If we can create a new LinkedIn app and request again o retry the complete flow from beginning.

Meanwhile, It would be a lot helpful if the app can throw some error alert messages (vague messages would do without exposing too much detail). Might help drill down the root cause.

Thanks for you time trying to replicate. Will get back if any issue, after trying out the flow freshly.

P.S. Let's keep this issue open, if thats's ok.

**Comment by bencgreenberg** [comment]
Yes, you're right. The app could definitely do with some better exposing the error. In this case, since you're not being prompted to sign in with LinkedIn once you click "Authorize LinkedIn", my guess is something is not correct in your LinkedIn developer settings, or the approval process for the Marketing API scope has not finished. There are so many steps with acquiring LinkedIn approval that it can get complicated.

**Comment by bencgreenberg** [comment]
@KRRISH96, I just merged a small improvement that should log and share at the top of the page the LinkedIn API error status code and message if the auth flow does not work. It's not a guarantee that the message from the LinkedIn API will be particularly meaningful, but it'll hopefully be some clue towards diagnosing the issue you're experiencing.

**Comment by KRRISH96** [comment]
@bencgreenberg Thanks for adding the error message.

The LinkedIn API response seems fine - `200` and `OK`

<img width="796" alt="Screenshot 2021-07-29 at 12 57 47 PM" src="https://user-images.githubusercontent.com/22497932/127450316-780cca9d-ea0a-4ba9-9c31-593a1f219806.png">

This is weird, status is 200 but still something wrong. BTW, this time after clicking the button it shows this message and redirects to the root path `/`.

**Comment by bencgreenberg** [comment]
That is so odd. I'm not sure what's going on for you here that it is not working.

I just tried again and replicated my workflow with the minor improvement I mentioned above to the app, and it worked again. I was able to retrieve an API token and I used it momentarily ago to successfully fetch my organization's LinkedIn posts.

The only reason why you would be redirected to the root path with a `200` status code is if there was no `location` object in the initial OAuth request to LinkedIn. This is what is used in the OAuth flow to direct you to the LinkedIn sign-in page after you click the "Authorize LinkedIn" blue button. 

Are you comfortable cloning this repository to your local machine, inserting a debugger like `pry` or `byebug` into the `#get_code_location` private method inside the `sessions_controller` and inspecting the details of the initial LinkedIn response?

**Comment by KRRISH96** [comment]
Yes, Ruby apps are no stranger to me. I will give it a try tomorrow.

**Comment by bencgreenberg** [comment]
Thanks. Let me know what you discover in that LinkedIn API response. If you can, share it here making sure to remove any credentials or identifying information.

**Comment by KRRISH96** [comment]
Hey @bencgreenberg ,

The Error Messages from LinkedIn is of no help.

Even for a failed auth, the response status is 200 with a HTML page for error page (maybe a redirect). So, no way to identify an error by status code alone (atleast in this scenario).

I did manually invoke the LinkedIn auth URL to see if it behaves any differently. And Yes, this time I got thrown into redirect page with message saying "You will be redirected to this URL `https://auth_callback_domain/auth/linkedin/callback?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_organization_social%26quot%3B+is+not+authorized+for+your+application`"

From this I got that the scope `r_organization_social` is not yet authorized for our application or maybe it did but different scope. Anyways, I will talk to my  organization's linkedin admin and see if we can re-auth or maybe create a new app and try the auth flow again.

With that info, I am sure that this might not be an issue with the app itself. I will close this for now and will re-open if encountered an issue specific to app.

Really appreciate your patience and time trying to figure this out. Thank You!

**Comment by bencgreenberg** [comment]
I am so glad you were able to get more clarity from that error message.

The thing I am taking away from that is to improve the experience by grabbing the `error` param in the callback URL, if it exists, and make that a friendly error message to display to the user.

If you need any more help, please feel free to reopen this, or join us on [Discord](https://discord.orbit.love).
